spring:
  profiles:
    active: DEV
  main: 
     lazy-initialization: true
     allow-bean-definition-overriding: true
  session:
     store-type: jdbc
     
  freemarker: 
    check-template-location: false
    
server:
  port: ${PORT:0}
  # ssl:
   # key-store: classpath:demo_indsolv.keystore
   # key-store-password: thirumal
  compression:
    enabled: true
 
---
feign:
    hystrix:
        enabled: true
---

logging: 
 level: 
  in.thirumal: debug
  org.springframework:
     jdbc.datasource.DataSourceTransactionManager: debug
     cloud.task: DEBUG
     security: 
        oauth2: debug
        jwt: debug
     http:
      converter: debug
---
spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/thirumal
    url: ${spring.datasource.jdbc-url}
    username: ENC(3469nU+3M46ULoBFP3VTaWLCKWeXC0tn)
    password: thirumal
    

---
freemarker:
  templateFolder: /fmtemplates
  

--- 
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
    appname: eureka-client-2
    leaseRenewalIntervalInSeconds: 10
#    homePageUrl: /2
#    status-page-url-path: /2/info
#    health-check-url-path: /2/actuator/health
    preferIpAddress: true
  client:
    enabled: true
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://thirumal:thirumal@localhost:8761/eureka/
      
spring:
  boot: 
    admin:
      client:
        instance:
          service-base-url: http://localhost:7126
        url: ${spring.boot.admin.client.instance.service-base-url}
        connect-timeout: 5000
  zipkin: 
    base-url: http://localhost:9411/  
 
springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
   